"""Tests for learning system Pydantic models."""

from __future__ import annotations

from astraea.learning.models import (
    CorrectionRecord,
    MappingExample,
    StudyMetrics,
    mapping_to_embedding_text,
)


class TestMappingExample:
    """Tests for MappingExample model."""

    def test_creation_with_defaults(self) -> None:
        """UUID and timestamp are generated by default."""
        example = MappingExample(
            study_id="STUDY001",
            domain="AE",
            sdtm_variable="AETERM",
            mapping_pattern="direct",
            mapping_logic="Direct carry from source",
            confidence=0.95,
            final_mapping_json='{"sdtm_variable": "AETERM"}',
        )
        assert example.example_id  # UUID generated
        assert len(example.example_id) == 32  # hex UUID
        assert example.created_at  # timestamp generated
        assert "T" in example.created_at  # ISO 8601 format
        assert example.was_corrected is False
        assert example.source_variable is None
        assert example.source_dataset is None
        assert example.source_label is None

    def test_creation_with_all_fields(self) -> None:
        """All fields can be set explicitly."""
        example = MappingExample(
            example_id="custom_id",
            study_id="STUDY001",
            domain="DM",
            sdtm_variable="USUBJID",
            mapping_pattern="derivation",
            mapping_logic="STUDYID || SITEID || SUBJID",
            source_variable="SUBJID",
            source_dataset="dm.sas7bdat",
            source_label="Subject Number",
            confidence=0.90,
            was_corrected=True,
            final_mapping_json='{"sdtm_variable": "USUBJID"}',
            created_at="2026-02-28T00:00:00+00:00",
        )
        assert example.example_id == "custom_id"
        assert example.source_variable == "SUBJID"
        assert example.source_dataset == "dm.sas7bdat"
        assert example.source_label == "Subject Number"
        assert example.was_corrected is True

    def test_round_trip_json(self) -> None:
        """MappingExample survives JSON serialization/deserialization."""
        original = MappingExample(
            study_id="STUDY001",
            domain="AE",
            sdtm_variable="AETERM",
            mapping_pattern="direct",
            mapping_logic="Direct carry",
            source_variable="AETERM",
            confidence=0.95,
            final_mapping_json='{"key": "value"}',
        )
        json_str = original.model_dump_json()
        restored = MappingExample.model_validate_json(json_str)
        assert restored.study_id == original.study_id
        assert restored.domain == original.domain
        assert restored.sdtm_variable == original.sdtm_variable
        assert restored.mapping_pattern == original.mapping_pattern
        assert restored.confidence == original.confidence
        assert restored.example_id == original.example_id


class TestCorrectionRecord:
    """Tests for CorrectionRecord model."""

    def test_creation_with_defaults(self) -> None:
        """UUID, timestamp, and invalidated default are set."""
        correction = CorrectionRecord(
            study_id="STUDY001",
            session_id="abc123def456",
            domain="AE",
            sdtm_variable="AEDECOD",
            correction_type="logic_change",
            original_pattern="direct",
            original_logic="Direct carry from AETERM",
            reason="Should use MedDRA preferred term lookup",
        )
        assert correction.correction_id  # UUID generated
        assert len(correction.correction_id) == 32
        assert correction.created_at
        assert correction.invalidated is False
        assert correction.corrected_pattern is None
        assert correction.corrected_logic is None

    def test_full_correction_with_corrected_fields(self) -> None:
        """Correction with both original and corrected fields."""
        correction = CorrectionRecord(
            study_id="STUDY001",
            session_id="abc123def456",
            domain="AE",
            sdtm_variable="AEDECOD",
            correction_type="logic_change",
            original_pattern="direct",
            corrected_pattern="derivation",
            original_logic="Direct carry from AETERM",
            corrected_logic="MedDRA preferred term lookup from AETERM",
            reason="AEDECOD requires dictionary coding",
        )
        assert correction.corrected_pattern == "derivation"
        assert correction.corrected_logic == "MedDRA preferred term lookup from AETERM"

    def test_invalidation_flag(self) -> None:
        """Invalidated flag can be set for poisoning protection."""
        correction = CorrectionRecord(
            study_id="STUDY001",
            session_id="abc123def456",
            domain="AE",
            sdtm_variable="AETERM",
            correction_type="source_change",
            original_pattern="direct",
            original_logic="From wrong source",
            reason="Wrong source variable",
            invalidated=True,
        )
        assert correction.invalidated is True


class TestStudyMetrics:
    """Tests for StudyMetrics model."""

    def test_accuracy_calculation(self) -> None:
        """Accuracy and correction rates are stored correctly."""
        metrics = StudyMetrics(
            study_id="STUDY001",
            domain="AE",
            total_proposed=20,
            approved_unchanged=15,
            corrected=3,
            rejected=1,
            added_by_reviewer=2,
            accuracy_rate=15 / 20,
            correction_rate=3 / 20,
            completed_at="2026-02-28T00:00:00+00:00",
        )
        assert metrics.accuracy_rate == 0.75
        assert metrics.correction_rate == 0.15
        assert metrics.total_proposed == 20

    def test_perfect_accuracy(self) -> None:
        """100% accuracy when all approved unchanged."""
        metrics = StudyMetrics(
            study_id="STUDY001",
            domain="DM",
            total_proposed=10,
            approved_unchanged=10,
            corrected=0,
            rejected=0,
            added_by_reviewer=0,
            accuracy_rate=1.0,
            correction_rate=0.0,
            completed_at="2026-02-28T00:00:00+00:00",
        )
        assert metrics.accuracy_rate == 1.0
        assert metrics.correction_rate == 0.0


class TestMappingToEmbeddingText:
    """Tests for the mapping_to_embedding_text helper."""

    def test_full_args(self) -> None:
        """All arguments produce structured sentence."""
        text = mapping_to_embedding_text(
            domain="AE",
            sdtm_variable="AETERM",
            mapping_pattern="direct",
            mapping_logic="Direct carry from source",
            source_variable="AETERM",
            source_label="Reported Term",
        )
        assert "SDTM domain AE variable AETERM" in text
        assert "mapping pattern: direct" in text
        assert "logic: Direct carry from source" in text
        assert "source variable: AETERM" in text
        assert "source label: Reported Term" in text

    def test_optional_args_omitted(self) -> None:
        """Optional args omitted produce shorter text without source info."""
        text = mapping_to_embedding_text(
            domain="DM",
            sdtm_variable="STUDYID",
            mapping_pattern="assign",
            mapping_logic="Constant value assignment",
        )
        assert "SDTM domain DM variable STUDYID" in text
        assert "mapping pattern: assign" in text
        assert "logic: Constant value assignment" in text
        assert "source variable" not in text
        assert "source label" not in text

    def test_only_source_variable_no_label(self) -> None:
        """Source variable without label includes variable but not label."""
        text = mapping_to_embedding_text(
            domain="AE",
            sdtm_variable="AESTDTC",
            mapping_pattern="reformat",
            mapping_logic="ISO 8601 date conversion",
            source_variable="AESTDT",
        )
        assert "source variable: AESTDT" in text
        assert "source label" not in text
